- name: Demo on Play varaibles
  hosts: all
  vars:
    URL: play.google.com
  tasks:
    - name: print URL
      debug:
      msg: URL {{ URL }}

- name: Demo on Play varaibles
  hosts: all

  tasks:
    - name: Print URL
      debug:
      vars:
        URL: tasks.example.com



