- name: Demo on Play varaibles
  hosts: all
  vars:
    URL: Play variables.com
  tasks:
    - name: print URL
      debug:
        msg: URL = {{ URL }}

- name: Demo on task varaibles
  hosts: all
  tasks:
    - name: print URL
      debug:
        msg: URL = {{ URL }}
      vars:
        URL: task.example.com

- name: Demo on CLI variables
  hosts: all
  tasks:
    - name: Print URL1 var from CLI
      debug:
        msg: URL1 = {{ URL1 }}








