- name: Demo on conditions
  hosts: all
  tasks:
    - name: execute if it is centos machine
      debug:
       msg: I am centos
      when: ansible_os_family == "RedHat"

    - name: execute if it is debain machine
      debug:
        msg: I am debain
      when: ansible_os_family == "Debain"