- name: Demo on conditions
  hosts: all
  tasks:
    - name: execute if it is centos machine
      debug:
       msg: I am centos

    - name: execute if it is debain machine
      debug:
        msg: I am debain