- name: setup Roboshop Project
  hosts: all
  become: yes
  tasks:
    - name: Import frontend
      ansible.builtin.import-role:
        name: frontend
      when: APP == "frontend"

    - name: catalogoe
      ansible.builtin.import-role:
        name: catalogue
      whenL APP == "catalogue"