- name: Demo on tags
  hosts: all
  tasks:
    - name: execute if it is centos machine
      debug:
        msg: I am centos
      tags:
        - redhat

    - name: execute if it is debain machine
      debug:
        msg: I am debain
      tags:
        - debain
