- name: Install Nginx
  ansible.builtin.yum:
    name: nginx
    state: present

- name: Download {{ APP }} Component
  include_role:
    name: common
    tasks_from: curl-download
  vars:
    URL: "https://github.com/roboshop-devops-project/frontend/archive/main.zip"
    EXTRACT_DIR: /usr/share/nginx/html


