- name: Download {{ APP }} Component
  get_url:
    url: "{{URL}}"
    dest: /tmp/{{APP}}.zip

- name: Remove old content
  file:
    path: "{{EXTRACT_PATH}}"
    state: absent

- name: Create direcory for {{ APP }} component
  file:
    path: "{{EXTRACT_PATH}}"
    state: directory

- name:  Unarchive {{ APP }}  Component
  ansible.builtin.unarchive:
    src: /tmp/{{APP}}.zip
    dest: "{{EXTRACT_PATH}}"
    remote_src: yes
